### ISSUE TITLE
Invite team

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2017#1]
@mikelmaron As per the slack comment,, can you please invite "donuzium" to this repo. Also can you update the repo description to 2017 please :-)

**Comment by tomhughes** [comment]
@RobJN by "invite" do you mean you want them given push access? Only you could do that yourself if you accepted the invite I sent you as you would then be an admin ;-)

**Comment by RobJN** [comment]
Thanks @tomhughes. It must have got lost in my inbox :-)
