### ISSUE TITLE
Program changes

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2017#108]
Hi @KMR-zoar 

Can you please make the following changes to the program page please:

- [x] Add details of our social event. This Saturday 18:00-20:00 at the Tsurugajo castle hall (http://tsurukan.com/ , http://www.openstreetmap.org/node/423793541). Last year we added the details to the "Overview" section at the top of the page. The OSM Awards will now happen at the social event.
- [x] Remove "OSM Awards" from the program (currently Saturday at 5:10pm).
- [x] Change the "End" time on Saturday to 5:20.
- [x] On Saturday morning we have an optional photo at Tsurugajo castle. Can we add this to the "overview" section at the top.
- [x] On Sunday we will be having an (optional) tour of the Fukushima Prefectural Museum. I have added it at 3:45pm in the program. Maybe we can add it to the "Overview" section too.

Also a big thank you for doing the website updates this year. It is wonderful that I do not need to worry about this as you do it so well and always very quickly :-D :+1:

**Comment by KMR-zoar** [comment]
@RobJN I updated program page for 5 items.

And I was able to work that because the support team and the Japanese community helped me, thank you.
