### ISSUE TITLE
map in english

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/stateofthemap-2017#117]
I like the map on the homepage, but maybe there should be another one on the venue page with markers, and a map showing the `name:en` names would be useful to a lot of people I think.

I've bookmarked this neat new multilingual map by OpenMapTiles, which does it well.
https://openmaptiles.org/languages/en/#14.85/37.489/139.9258/0.6/2

But that site's not actually very useable because it's just a demo site, and has a white strip across it. So... well maybe this website would be a good place to deploy it without the white strip.

I think it might be a bit cpi/bandwidth heavy, so it could be that this suggestion is best kept for  a separate page e.g http://2017.stateofthemap.org/map

(I'd look into implementing this myself, but I should finish preparing my SOTM talk!)

**Comment by Firefishy** [comment]
Closing as stale.
