### ISSUE TITLE
Edit the newsletter section.

### ISSUE THREAD

**Issue by KMR-zoar** [openstreetmap/stateofthemap-2017#132]
I am considering editing the newsletter section, Because section was written "Registration is now open.".

can this year's newsletter registered members receive information next or newer SotM?

When system works that way, I will edit to "By registering in the newsletter you will be able to get future State of the Map information quickly.".

When system __*not*__ work that way, I remove newsletter section.

**Comment by RobJN** [comment]
> can this year's newsletter registered members receive information next or newer SotM?

Yes.

So you can keep this section and change the text.

Thanks

**Comment by KMR-zoar** [comment]
Thanks for quick response.
I will edit it immediately.

I will add a hash to each session markdown once the video is split.

Thanks to everyone, it was a very fun event!
