### ISSUE TITLE
Logo is hard to see on the backgroud image

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2017#15]
The background image is pixelated as @RobJN compressed it too much! Also the logo is difficult to see on it.

It may help to just brighten the background image, or layer a semi-opacity on top.

@KMR-zoar Is this something you could try to fix please?

**Comment by KMR-zoar** [comment]
Yes, I will work in this issue.

I think the following ways.

+ Trim images, at the time move the center of image.
+ And add layer a semi-opacity, between the logo to background-image.

**Comment by KMR-zoar** [comment]
I thought that this problem was solved because pull requests were merged.
