### ISSUE TITLE
Map needs sorting

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2017#16]
Mikel wrote:

>yea, we can use a different basemap -- just needs to be set up with an account. i think last year was on Tatiana's account. we should probably create a SotM mb account, and I can arrange coupon to cover costs 

One for you then @mikelmaron :-)

**Comment by mikelmaron** [comment]
I've switched the map over to 'stateofthemap' account, and recentered over the venue. could use some design love, but it does the job for now
