### ISSUE TITLE
Colors and other design elements

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2017#18]
How are the colors looking? I've got the worlds worst LCD monitor to judge this. Maybe @mikelmaron could grab a Mapbox design hero for 5 mins during a lunch break for some advice... :-D

**Comment by RobJN** [comment]
Also check the mouse-over colors as some of these seem a bit off. Let's create a list of bits that need changing.

P.s. We could also search around for existing sites using a similar color scheme.

**Comment by Firefishy** [comment]
Closing as stale
