### ISSUE TITLE
Website in Japanese

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2017#19]
Last year we decided that English was sufficient for the website. This year we need to do both English and Japanese.

How can translations be added to the website? Does Jekyll provide anything to make this easy?

This is possibly something for @KMR-zoar to look at. We can get Daniel to help with the translations, but step 1 is to find out how to set it up on the website.

**Comment by KMR-zoar** [comment]
* Copying contents to ja/ path and replace EN to JA.

It's seems simple , but I am worried about discrepancies in contents.

* Use plugin for jekyll

There were some plugins in the range I examied.
e.g. [Jekyll Language Plugin](https://github.com/vwochnik/jekyll-language-plugin)

This way seems to have to change all existing pages as well.

Is there any other good way?

**Comment by donuzium** [comment]
@KMR-zoar I appreciate to your working. Thank you very much.

I think copying contents is a simple way.

There's a plugin for jQuery to localize site contents, but a script will be a bit complicate.
And it needs a little waiting time until localized contents is display when the page loaded.
https://github.com/coderifous/jquery-localize

I usually make site with AngularJS (ver 1) that has a good function for multi language site. But changing to use AngularJS is complicated, too...

**Comment by KMR-zoar** [comment]
@donuzium ありがとうございます、お元気なようで安心しました。
Thank you, I am relieved to be fine.

@RobJN Does the newsletter work without problems when making Japanese version by copying?

I think that is undesirable for news letter to be sent both in English editing and in Japanese editing.
Is the system sending Japanese updates to English speakers?

**Comment by RobJN** [comment]
@KMR-zoar The newsletter sign-up form links to MailChimp. From mailchimp we can send emails. We have two options:

1. Copy as is (leaving it linked to the current MailChimp list) - we won't know who signed up via the Japanese language website
2. Set-up an extra list in MailChimp for Japanese only website.

I'm happy with either.

When could you get the Japanese translation of the website finished by?

**Comment by KMR-zoar** [comment]
@RobJN I just pushed the file copied it to Japanese. pull #32

We choose 1st option. talked to the Japanese community.
There is no bandwidth to publish a Japanese newsletter, We attach a note of Japanese newsletter "ニュースレターは英語で届きます"(Meaning:Newsletter is only English).

**Comment by mikelmaron** [comment]
@KMR-zoar I've merged https://github.com/openstreetmap/stateofthemap-2017/pull/32 :)

Two things
* no manual way to switch to Japanese version. is this based on browser language detection?
* header and footer still in English in Japanese version

**Comment by KMR-zoar** [comment]
@RobJN Thanks for the merge.

Automatic language detection is not supported that PR. Language detection and automatically switch pages is outside my current skill....
I just made "ja/" path and copied translated files.
Header and footer are not tanslated into Japanese at Japanese files. Because that's easy English words.

**Comment by KMR-zoar** [comment]
I tried it with two approaches.

1. Automatic switch by language, using javascript
pull #34

2. Added link to allow users to switch languages by themselves, at navbar
pull #35

Opt.1 success displaying Japanese and English. I just tried it with only a Chrome.

**Comment by RobJN** [comment]
I accepted both PRs but now have a problem. If you automatically switch to Japanese based on browser language you cannot then switch to English using the navbar as the javascript keeps switching back.

I guess this is not too much of a problem. If it is then my preference is Option 2 as this works even if your browser is not set up correctly.

Alternatively is it possible to have both options but remember if English is selected from the navbar?

**Comment by KMR-zoar** [comment]
I preference choose option 2, because navbar is not remember English selected.

I think that JavaScript has the possibility of doing unexpected work.

**Comment by RobJN** [comment]
Have reverted #34 so we just have option 2 live now.

Closing but feel free to re-open if more comments.
