### ISSUE TITLE
sub pages nav has white text on white background

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/stateofthemap-2017#27]
![screen shot 2017-02-27 at 10 50 34 am](https://cloud.githubusercontent.com/assets/22896/23368076/97e1c1d2-fcda-11e6-9fda-997ebb67f12c.png)

**Comment by KMR-zoar** [comment]
I suggest a pull request as a solution to this issue.
pull #29

**Comment by KMR-zoar** [comment]
I made two images but forgot to put it in my comment.

in index.html
![capture2](https://cloud.githubusercontent.com/assets/6219187/23446826/ee111746-fe89-11e6-870a-178477fae2cc.PNG)

except index.html
![capture](https://cloud.githubusercontent.com/assets/6219187/23446841/ff49a9b0-fe89-11e6-8633-e0984c7fe629.PNG)
