### ISSUE TITLE
Sponsorship links

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/stateofthemap-2017#33]
Let's link to something actionable on the Sponsorship section -- either a link to download the prospectus or to email

@RobJN @KMR-zoar

**Comment by RobJN** [comment]
The "Your logo here" links to the email (same as last year's site). Obviously too subtle so best to add some text to this block.

**Comment by KMR-zoar** [comment]
For now. I added simple sentences, I could not think of a good copy.
PR #37
