### ISSUE TITLE
Preparation for program table

### ISSUE THREAD

**Issue by KMR-zoar** [openstreetmap/stateofthemap-2017#56]
In order to display the program table, it is necessary to use the 2016's files and part of the 2016's css file.

**Comment by KMR-zoar** [comment]
Will edit on css, _include and _layout the range that does not affect other pages.

**Comment by RobJN** [comment]
Pull request #64 added the md files for day 1 and day 2. I still need more time to do day 3 workshops. Is it okay to start with the first 2 days?

---
I have created the md files for day 1 and day 2 (main 20 minute talks).

Notes:

- I have added "audience" and "audience_full" and populated this with data from the talk proposal sheet. So far this is not used but maybe @KMR-zoar can update the way the website displays the program so as to show the target audience (probably do this on the individual page, not the /program page as that would become too cluttered).
- I have added "theme_full" and taken this from the talk proposal sheet.
- I have populated "theme" and "category" with what I think is the best fit from "theme_full". Note that these are therefore **different** themes from last year. I am not sure how we should show the theme this year. Maybe the same was as I propose to show the target audience. @mikelmaron What do you think?

The program schedule can be found on the "Schedule" tab of the talk proposals google sheet. I will share a link via Slack so as to not make this public.

P.s. There may be errors but hopefully not too many and only individual md files.

**Comment by KMR-zoar** [comment]
Yes, I can start with the first 2 days.

And I can display 'audience' on program table and each session pages. But letter is overlap on program table sometimes by display size, when displaying 'theme' and 'audience'.

Is discussion comment field necessary for each session pages?
It seems that it was not used(or It used was a bit) in last year.

**Comment by KMR-zoar** [comment]
I think the creation of the basic program table was completed by PR #78. please make another issue if problems occur.
