### ISSUE TITLE
The order of the room names is incorrect at program table.

### ISSUE THREAD

**Issue by KMR-zoar** [openstreetmap/stateofthemap-2017#66]
Session display order depends to MD filename sort.
There are cases where the main hole is on the left side and the case on the right side.

![default](https://cloud.githubusercontent.com/assets/6219187/26730266/43b878c4-47eb-11e7-91b9-c3814cc13ff1.PNG)

**Comment by KMR-zoar** [comment]
This problem is solved by changing the MD filename.
Will change this to be the same as the 2016 naming convention.

0200-01-0X-*.md

Currently X shows the number of days.
-> Assign X by the room name.
When X = 1, Main hall
When X = 2, Room 1

You can know the number of days by the number of slots in the MD file. 
(The slot number has been changed with commit 9c03f22c9f725737b6b272a77b524985e16caaee.)

**Comment by RobJN** [comment]
We had this issue at one stage last year. @tatsvc fixed it but not sure how and we no longer have her time to help us.

Do we know what the "0200-01-" in the file names is for, if anything? If I understood, we could make this better for next year (SotM 2018).

cc @mikelmaron

**Comment by KMR-zoar** [comment]
Jekyll docs is saying that date string(Year-month-date): https://learn.cloudcannon.com/jekyll/introduction-to-blogging/#creating-a-post
Originally it seems to be for handling blog posts.

We maybe able to change it with _config.yml setting. But I do not know how to set it now.

**Comment by KMR-zoar** [comment]
I think that "for" written in Liquid is registering MD files in filename order.
It maybe possible to change the display order by setting css property, but unfortunately I am not good at CSS.

**Comment by RobJN** [comment]
You might be able to find the edit that was made to the 2016 website (https://github.com/openstreetmap/stateofthemap-2016) but no need -> just do what's easiest for you :-D

**Comment by mikelmaron** [comment]
@RobJN @KMR-zoar I can take a look after the weekend

**Comment by KMR-zoar** [comment]
I think that the display order is correct with commit 63c5cc7ff9211ac67397f89509cdab504b91a964.
It is welcome to find a problems!

**Comment by mikelmaron** [comment]
@RobJN are we planning to categorize the talks, like last year?

**Comment by RobJN** [comment]
@mikelmaron I'm not planning to do this. We got a bit of criticism last year for getting the theme of some talks slightly wrong. This year we asked for "theme" and "audience" according to the list on https://wiki.openstreetmap.org/wiki/State_Of_The_Map/Planning/Vision#Conference_attendance

The MD files include those that the speaker ticked. I then selected the most appropriate (which for audience isn't easy as lots of overlap) and the program shows this. Example:
http://2017.stateofthemap.org/2017/osm-in-aizuwakamatsu-city-construction-of-a-hazard-map/

We could change it so that the page shows the full list of all themes and audiences that the speaker picked. How about that?

**Comment by KMR-zoar** [comment]
When we display the theme and audience in the items of the program, it looks like this.

![default](https://cloud.githubusercontent.com/assets/6219187/26813895/726238c6-4abc-11e7-92d1-4ace032eca08.PNG)

In order to display them have to increase the height of the item and narrow the line spacing.

To apply this change you can verify by merging the "zoar-patch4" branch.

**Comment by mikelmaron** [comment]
@KMR-zoar that presentation looks really crowded. Can you remove "Audience", and consider using the approach from last year -- an interactive theme, color coded theme selector.
![screen shot 2017-06-20 at 8 08 57 am](https://user-images.githubusercontent.com/22896/27332415-c8b84ebc-558f-11e7-8a47-9416a8efd36b.png)

**Comment by KMR-zoar** [comment]
@mikelmaron Since "zoar-patch4" branch has not been approved, I did not merge. Theme and Audience is not displayed in the table now. I think that merging this branch will make the table look crowded.

Currently "category" filter cannot be work. Because the value of "category" key in MD files is not the same as last year's value. In order to make that function effective, one of the following methods is necessary.

1. Edit the category filter command, layout files and CSS files
-> I'm not an IT engineer so I do not know how long it will take for the this edit.

1. Rewrite value of "category" key with reference to value of the last year
-> I may not be able to set the correct value of "category" key because I am not fluent in English.
We will also need to access the speakers and check them, just as @RobJN did when setting themes, I don't have that channel.

I don't feel necessity that "category" filter now. (but I have a slight technical interest in former.)

**Comment by KMR-zoar** [comment]
@mikelmaron I'm trying enabled the "category" filter in PR #93 by Opt.1. Temporarily enable it, or testing it locally.

I'm happy if you like it, but please let me know if there are fix points.

Run the filter:
![category-filter](https://user-images.githubusercontent.com/6219187/27522848-09d1d098-5a64-11e7-8aee-260e683f82ea.PNG)

Category colors:
![categorys1](https://user-images.githubusercontent.com/6219187/27522853-0f5e8998-5a64-11e7-83a1-b7b17dd80713.PNG)
![categorys2](https://user-images.githubusercontent.com/6219187/27522855-127f3230-5a64-11e7-8cf4-07b8e72b670c.PNG)
![categorys3](https://user-images.githubusercontent.com/6219187/27522857-14e6413a-5a64-11e7-8d90-63e7df2638e7.PNG)

**Comment by mikelmaron** [comment]
@KMR-zoar where did you get the category names from? They are long, I suggest we edit them down to 

* Cartography / visualization
* Data creation
* Humanitarian
* Data use and analysis
* Intro to OSM
* Technical
* Local community
* Organization and legal
* Transport and planning

**Comment by KMR-zoar** [comment]
@mikelmaron Thank you for the advice. The category names is acquired from the header of program/index.html(ja/program/index.html).
I made a new PR #94 .

![categories1](https://user-images.githubusercontent.com/6219187/27524735-ef356e7a-5a72-11e7-896c-fb663fb958e2.PNG)
![categories2](https://user-images.githubusercontent.com/6219187/27524736-f190f7de-5a72-11e7-9d3f-a5a047ec0de7.PNG)

**Comment by Firefishy** [comment]
Closing due to age. If still relevant, feel free to re-open.
