### ISSUE TITLE
The announce section follows event of the OSM Award.

### ISSUE THREAD

**Issue by KMR-zoar** [openstreetmap/stateofthemap-2017#89]
Follows OSM Award events.
First of all, [Call for nominees](https://blog.openstreetmap.org/2017/06/19/nominees-openstreetmap-awards/), the deadline is July 9th. The second round will start after that day.

**Comment by KMR-zoar** [comment]
Merged Call for nominees.
I'm going to make a next edit around the starting second round.

**Comment by KMR-zoar** [comment]
Call for nominees for the OSM Awards has ended.

Wait for the update of the next step.

**Comment by KMR-zoar** [comment]
Vote is staring, and change announce section.

**Comment by RobJN** [comment]
I have now removed the announce section so that the page is cleaner ready for SotM.
